dist: xenial
language: python
python:
- 2.7
- 3.5
branches:
  only:
    - master
install:
  - pip install -r requirements/travis.txt
script:
  - sudo rm -f /etc/boto.cfg && python manage.py test notifier
after_success:
  - coveralls
